# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.pagination import AsyncPager, SyncPager
from ...core.request_options import RequestOptions
from ...types.add_hyperedge_edge_result import AddHyperedgeEdgeResult
from ...types.add_hyperedge_result import AddHyperedgeResult
from ...types.async_result import AsyncResult
from ...types.edge_node_ref import EdgeNodeRef
from ...types.hyperedge import Hyperedge
from ...types.hyperedge_input import HyperedgeInput
from ...types.hyperedge_page import HyperedgePage
from .raw_client import AsyncRawHyperedgeClient, RawHyperedgeClient
from .types.hyperedge_list_request_order import HyperedgeListRequestOrder
from .types.hyperedge_list_request_order_by import HyperedgeListRequestOrderBy

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class HyperedgeClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawHyperedgeClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawHyperedgeClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawHyperedgeClient
        """
        return self._raw_client

    def add(
        self,
        graph_uuid: str,
        *,
        edges: typing.Sequence[HyperedgeInput],
        fact: str,
        attributes: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        expired_at: typing.Optional[str] = OMIT,
        invalid_at: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        valid_at: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AddHyperedgeResult:
        """
        Creates one hyperedge: a fact that relates more than two nodes, written
        onto one member edge per node pair. The member edges must span at least
        three distinct nodes, since two nodes are a pair of edges rather than a
        hyperedge; a single pair uses graph.edge.add. Zep assigns the hyperedge
        identifier and every member edge identifier at accept time, and the
        members become readable when the task completes.

        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        edges : typing.Sequence[HyperedgeInput]
            The member edges to create. Each pair becomes one edge carrying the
            shared fact.

        fact : str
            The natural-language fact, written onto every member edge.

        attributes : typing.Optional[typing.Dict[str, typing.Any]]
            Additional attributes to store on every member edge.

        expired_at : typing.Optional[str]
            The time at which the fact was superseded or invalidated.

        invalid_at : typing.Optional[str]
            The time at which the fact stopped being true.

        metadata : typing.Optional[typing.Dict[str, typing.Any]]
            Metadata attached to the episode created for this hyperedge.

        valid_at : typing.Optional[str]
            The time at which the fact became true.

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AddHyperedgeResult
            Accepted

        Examples
        --------
        from zep_cloud import EdgeNodeRef, HyperedgeInput, Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        client.graph.hyperedge.add(
            graph_uuid="graph_uuid",
            edges=[
                HyperedgeInput(
                    name="name",
                    source_node=EdgeNodeRef(),
                    target_node=EdgeNodeRef(),
                )
            ],
            fact="fact",
        )
        """
        _response = self._raw_client.add(
            graph_uuid,
            edges=edges,
            fact=fact,
            attributes=attributes,
            expired_at=expired_at,
            invalid_at=invalid_at,
            metadata=metadata,
            valid_at=valid_at,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    def list(
        self,
        graph_uuid: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        order_by: typing.Optional[HyperedgeListRequestOrderBy] = None,
        order: typing.Optional[HyperedgeListRequestOrder] = None,
        filters: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[Hyperedge, HyperedgePage]:
        """
        Returns the graph's hyperedges. A hyperedge is listed while it has at
        least one member edge. Supported filters are node_uuids, edge_uuids and
        episode_uuids: a hyperedge matches a list when any of its members does,
        and must match every list supplied.

        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        limit : typing.Optional[int]
            Page size

        cursor : typing.Optional[str]
            Opaque page cursor

        order_by : typing.Optional[HyperedgeListRequestOrderBy]
            Sort key: uuid or created_at

        order : typing.Optional[HyperedgeListRequestOrder]
            Sort direction: asc or desc

        filters : typing.Optional[typing.Dict[str, typing.Any]]
            Filters constraining which items are returned.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[Hyperedge, HyperedgePage]
            OK

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        response = client.graph.hyperedge.list(
            graph_uuid="graph_uuid",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list(
            graph_uuid,
            limit=limit,
            cursor=cursor,
            order_by=order_by,
            order=order,
            filters=filters,
            request_options=request_options,
        )

    def get(
        self, graph_uuid: str, hyperedge_uuid: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> Hyperedge:
        """
        Returns one hyperedge assembled from its member edges. The fact and the
        validity timestamps are shared by every member and are reported on the
        hyperedge; each member reports only its own name and endpoints.

        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        hyperedge_uuid : str
            Hyperedge UUID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Hyperedge
            OK

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        client.graph.hyperedge.get(
            graph_uuid="graph_uuid",
            hyperedge_uuid="hyperedge_uuid",
        )
        """
        _response = self._raw_client.get(graph_uuid, hyperedge_uuid, request_options=request_options)
        return _response.data

    def delete(
        self,
        graph_uuid: str,
        hyperedge_uuid: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncResult:
        """
        Deletes every member edge of the hyperedge. After the task completes the
        hyperedge and each of its members are gone.

        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        hyperedge_uuid : str
            Hyperedge UUID

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncResult
            Accepted

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        client.graph.hyperedge.delete(
            graph_uuid="graph_uuid",
            hyperedge_uuid="hyperedge_uuid",
        )
        """
        _response = self._raw_client.delete(
            graph_uuid, hyperedge_uuid, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    def update(
        self,
        graph_uuid: str,
        hyperedge_uuid: str,
        *,
        fact: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Hyperedge:
        """
        Updates the shared fact and writes it onto every member edge in one
        all-or-nothing write: either every member carries the new fact or none
        does. Only fact is accepted, because it is the only field the members
        share. name belongs to each member edge, and membership changes use
        create_edge and delete_edge. Updating fact on one member through
        graph.edge.update cascades the same way.

        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        hyperedge_uuid : str
            Hyperedge UUID

        fact : typing.Optional[str]
            The natural-language fact, rewritten onto every member edge.

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Hyperedge
            OK

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        client.graph.hyperedge.update(
            graph_uuid="graph_uuid",
            hyperedge_uuid="hyperedge_uuid",
        )
        """
        _response = self._raw_client.update(
            graph_uuid, hyperedge_uuid, fact=fact, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    def create_edge(
        self,
        graph_uuid: str,
        hyperedge_uuid: str,
        *,
        name: str,
        source_node: EdgeNodeRef,
        target_node: EdgeNodeRef,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AddHyperedgeEdgeResult:
        """
        Adds one member edge to an existing hyperedge. The new member inherits the
        hyperedge's fact and timestamps and joins its episodes, so only its own
        name and node pair are supplied.

        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        hyperedge_uuid : str
            Hyperedge UUID

        name : str
            The name of the new member edge, in upper snake case.

        source_node : EdgeNodeRef
            The source node of the new member.

        target_node : EdgeNodeRef
            The target node of the new member.

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AddHyperedgeEdgeResult
            Accepted

        Examples
        --------
        from zep_cloud import EdgeNodeRef, Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        client.graph.hyperedge.create_edge(
            graph_uuid="graph_uuid",
            hyperedge_uuid="hyperedge_uuid",
            name="name",
            source_node=EdgeNodeRef(),
            target_node=EdgeNodeRef(),
        )
        """
        _response = self._raw_client.create_edge(
            graph_uuid,
            hyperedge_uuid,
            name=name,
            source_node=source_node,
            target_node=target_node,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    def delete_edge(
        self,
        graph_uuid: str,
        hyperedge_uuid: str,
        edge_uuid: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncResult:
        """
        Removes one member edge from the hyperedge. The remaining members stay in
        the hyperedge, and deleting the last member removes the hyperedge itself.

        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        hyperedge_uuid : str
            Hyperedge UUID

        edge_uuid : str
            Edge UUID

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncResult
            Accepted

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        client.graph.hyperedge.delete_edge(
            graph_uuid="graph_uuid",
            hyperedge_uuid="hyperedge_uuid",
            edge_uuid="edge_uuid",
        )
        """
        _response = self._raw_client.delete_edge(
            graph_uuid, hyperedge_uuid, edge_uuid, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data


class AsyncHyperedgeClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawHyperedgeClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawHyperedgeClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawHyperedgeClient
        """
        return self._raw_client

    async def add(
        self,
        graph_uuid: str,
        *,
        edges: typing.Sequence[HyperedgeInput],
        fact: str,
        attributes: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        expired_at: typing.Optional[str] = OMIT,
        invalid_at: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        valid_at: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AddHyperedgeResult:
        """
        Creates one hyperedge: a fact that relates more than two nodes, written
        onto one member edge per node pair. The member edges must span at least
        three distinct nodes, since two nodes are a pair of edges rather than a
        hyperedge; a single pair uses graph.edge.add. Zep assigns the hyperedge
        identifier and every member edge identifier at accept time, and the
        members become readable when the task completes.

        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        edges : typing.Sequence[HyperedgeInput]
            The member edges to create. Each pair becomes one edge carrying the
            shared fact.

        fact : str
            The natural-language fact, written onto every member edge.

        attributes : typing.Optional[typing.Dict[str, typing.Any]]
            Additional attributes to store on every member edge.

        expired_at : typing.Optional[str]
            The time at which the fact was superseded or invalidated.

        invalid_at : typing.Optional[str]
            The time at which the fact stopped being true.

        metadata : typing.Optional[typing.Dict[str, typing.Any]]
            Metadata attached to the episode created for this hyperedge.

        valid_at : typing.Optional[str]
            The time at which the fact became true.

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AddHyperedgeResult
            Accepted

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep, EdgeNodeRef, HyperedgeInput

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.graph.hyperedge.add(
                graph_uuid="graph_uuid",
                edges=[
                    HyperedgeInput(
                        name="name",
                        source_node=EdgeNodeRef(),
                        target_node=EdgeNodeRef(),
                    )
                ],
                fact="fact",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.add(
            graph_uuid,
            edges=edges,
            fact=fact,
            attributes=attributes,
            expired_at=expired_at,
            invalid_at=invalid_at,
            metadata=metadata,
            valid_at=valid_at,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    async def list(
        self,
        graph_uuid: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        order_by: typing.Optional[HyperedgeListRequestOrderBy] = None,
        order: typing.Optional[HyperedgeListRequestOrder] = None,
        filters: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[Hyperedge, HyperedgePage]:
        """
        Returns the graph's hyperedges. A hyperedge is listed while it has at
        least one member edge. Supported filters are node_uuids, edge_uuids and
        episode_uuids: a hyperedge matches a list when any of its members does,
        and must match every list supplied.

        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        limit : typing.Optional[int]
            Page size

        cursor : typing.Optional[str]
            Opaque page cursor

        order_by : typing.Optional[HyperedgeListRequestOrderBy]
            Sort key: uuid or created_at

        order : typing.Optional[HyperedgeListRequestOrder]
            Sort direction: asc or desc

        filters : typing.Optional[typing.Dict[str, typing.Any]]
            Filters constraining which items are returned.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[Hyperedge, HyperedgePage]
            OK

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.graph.hyperedge.list(
                graph_uuid="graph_uuid",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list(
            graph_uuid,
            limit=limit,
            cursor=cursor,
            order_by=order_by,
            order=order,
            filters=filters,
            request_options=request_options,
        )

    async def get(
        self, graph_uuid: str, hyperedge_uuid: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> Hyperedge:
        """
        Returns one hyperedge assembled from its member edges. The fact and the
        validity timestamps are shared by every member and are reported on the
        hyperedge; each member reports only its own name and endpoints.

        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        hyperedge_uuid : str
            Hyperedge UUID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Hyperedge
            OK

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.graph.hyperedge.get(
                graph_uuid="graph_uuid",
                hyperedge_uuid="hyperedge_uuid",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(graph_uuid, hyperedge_uuid, request_options=request_options)
        return _response.data

    async def delete(
        self,
        graph_uuid: str,
        hyperedge_uuid: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncResult:
        """
        Deletes every member edge of the hyperedge. After the task completes the
        hyperedge and each of its members are gone.

        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        hyperedge_uuid : str
            Hyperedge UUID

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncResult
            Accepted

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.graph.hyperedge.delete(
                graph_uuid="graph_uuid",
                hyperedge_uuid="hyperedge_uuid",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(
            graph_uuid, hyperedge_uuid, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    async def update(
        self,
        graph_uuid: str,
        hyperedge_uuid: str,
        *,
        fact: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Hyperedge:
        """
        Updates the shared fact and writes it onto every member edge in one
        all-or-nothing write: either every member carries the new fact or none
        does. Only fact is accepted, because it is the only field the members
        share. name belongs to each member edge, and membership changes use
        create_edge and delete_edge. Updating fact on one member through
        graph.edge.update cascades the same way.

        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        hyperedge_uuid : str
            Hyperedge UUID

        fact : typing.Optional[str]
            The natural-language fact, rewritten onto every member edge.

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Hyperedge
            OK

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.graph.hyperedge.update(
                graph_uuid="graph_uuid",
                hyperedge_uuid="hyperedge_uuid",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            graph_uuid, hyperedge_uuid, fact=fact, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    async def create_edge(
        self,
        graph_uuid: str,
        hyperedge_uuid: str,
        *,
        name: str,
        source_node: EdgeNodeRef,
        target_node: EdgeNodeRef,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AddHyperedgeEdgeResult:
        """
        Adds one member edge to an existing hyperedge. The new member inherits the
        hyperedge's fact and timestamps and joins its episodes, so only its own
        name and node pair are supplied.

        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        hyperedge_uuid : str
            Hyperedge UUID

        name : str
            The name of the new member edge, in upper snake case.

        source_node : EdgeNodeRef
            The source node of the new member.

        target_node : EdgeNodeRef
            The target node of the new member.

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AddHyperedgeEdgeResult
            Accepted

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep, EdgeNodeRef

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.graph.hyperedge.create_edge(
                graph_uuid="graph_uuid",
                hyperedge_uuid="hyperedge_uuid",
                name="name",
                source_node=EdgeNodeRef(),
                target_node=EdgeNodeRef(),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_edge(
            graph_uuid,
            hyperedge_uuid,
            name=name,
            source_node=source_node,
            target_node=target_node,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    async def delete_edge(
        self,
        graph_uuid: str,
        hyperedge_uuid: str,
        edge_uuid: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncResult:
        """
        Removes one member edge from the hyperedge. The remaining members stay in
        the hyperedge, and deleting the last member removes the hyperedge itself.

        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        hyperedge_uuid : str
            Hyperedge UUID

        edge_uuid : str
            Edge UUID

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncResult
            Accepted

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.graph.hyperedge.delete_edge(
                graph_uuid="graph_uuid",
                hyperedge_uuid="hyperedge_uuid",
                edge_uuid="edge_uuid",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_edge(
            graph_uuid, hyperedge_uuid, edge_uuid, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data
