# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.search_filters import SearchFilters
from ...types.thread_summary import ThreadSummary
from .raw_client import AsyncRawThreadSummaryClient, RawThreadSummaryClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ThreadSummaryClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawThreadSummaryClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawThreadSummaryClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawThreadSummaryClient
        """
        return self._raw_client

    def get_by_graph_id(
        self,
        graph_id: str,
        *,
        cursor: typing.Optional[str] = OMIT,
        direction: typing.Optional[str] = OMIT,
        filters: typing.Optional[SearchFilters] = OMIT,
        limit: typing.Optional[int] = OMIT,
        order_by: typing.Optional[str] = OMIT,
        uuid_cursor: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[ThreadSummary]:
        """
        Returns incremental thread summaries associated with the graph.

        Parameters
        ----------
        graph_id : str
            Graph ID

        cursor : typing.Optional[str]
            Opaque cursor for pagination, obtained from the Zep-Next-Cursor response header
            of the previous page. Encodes the sort field, direction, and continuation position.

        direction : typing.Optional[str]
            Sort direction. One of "asc" or "desc" (default "desc").

        filters : typing.Optional[SearchFilters]
            Optional filters applied to the listed artifacts. Reuses the graph.search filter type.

        limit : typing.Optional[int]
            Maximum number of items to return

        order_by : typing.Optional[str]
            Field to sort by. One of "created_at" or "uuid" (default "uuid").

        uuid_cursor : typing.Optional[str]
            UUID based cursor, used for pagination. Should be the UUID of the last item in the previous page.

            Deprecated: prefer Cursor, the opaque cursor returned via the Zep-Next-Cursor response header.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ThreadSummary]
            Thread summaries

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        client.graph.thread_summary.get_by_graph_id(
            graph_id="graph_id",
        )
        """
        _response = self._raw_client.get_by_graph_id(
            graph_id,
            cursor=cursor,
            direction=direction,
            filters=filters,
            limit=limit,
            order_by=order_by,
            uuid_cursor=uuid_cursor,
            request_options=request_options,
        )
        return _response.data

    def get_by_user_id(
        self,
        user_id: str,
        *,
        cursor: typing.Optional[str] = OMIT,
        direction: typing.Optional[str] = OMIT,
        filters: typing.Optional[SearchFilters] = OMIT,
        limit: typing.Optional[int] = OMIT,
        order_by: typing.Optional[str] = OMIT,
        uuid_cursor: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[ThreadSummary]:
        """
        Returns incremental thread summaries generated from messages in each thread associated with the user's graph.

        Parameters
        ----------
        user_id : str
            User ID

        cursor : typing.Optional[str]
            Opaque cursor for pagination, obtained from the Zep-Next-Cursor response header
            of the previous page. Encodes the sort field, direction, and continuation position.

        direction : typing.Optional[str]
            Sort direction. One of "asc" or "desc" (default "desc").

        filters : typing.Optional[SearchFilters]
            Optional filters applied to the listed artifacts. Reuses the graph.search filter type.

        limit : typing.Optional[int]
            Maximum number of items to return

        order_by : typing.Optional[str]
            Field to sort by. One of "created_at" or "uuid" (default "uuid").

        uuid_cursor : typing.Optional[str]
            UUID based cursor, used for pagination. Should be the UUID of the last item in the previous page.

            Deprecated: prefer Cursor, the opaque cursor returned via the Zep-Next-Cursor response header.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ThreadSummary]
            Thread summaries

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        client.graph.thread_summary.get_by_user_id(
            user_id="user_id",
        )
        """
        _response = self._raw_client.get_by_user_id(
            user_id,
            cursor=cursor,
            direction=direction,
            filters=filters,
            limit=limit,
            order_by=order_by,
            uuid_cursor=uuid_cursor,
            request_options=request_options,
        )
        return _response.data


class AsyncThreadSummaryClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawThreadSummaryClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawThreadSummaryClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawThreadSummaryClient
        """
        return self._raw_client

    async def get_by_graph_id(
        self,
        graph_id: str,
        *,
        cursor: typing.Optional[str] = OMIT,
        direction: typing.Optional[str] = OMIT,
        filters: typing.Optional[SearchFilters] = OMIT,
        limit: typing.Optional[int] = OMIT,
        order_by: typing.Optional[str] = OMIT,
        uuid_cursor: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[ThreadSummary]:
        """
        Returns incremental thread summaries associated with the graph.

        Parameters
        ----------
        graph_id : str
            Graph ID

        cursor : typing.Optional[str]
            Opaque cursor for pagination, obtained from the Zep-Next-Cursor response header
            of the previous page. Encodes the sort field, direction, and continuation position.

        direction : typing.Optional[str]
            Sort direction. One of "asc" or "desc" (default "desc").

        filters : typing.Optional[SearchFilters]
            Optional filters applied to the listed artifacts. Reuses the graph.search filter type.

        limit : typing.Optional[int]
            Maximum number of items to return

        order_by : typing.Optional[str]
            Field to sort by. One of "created_at" or "uuid" (default "uuid").

        uuid_cursor : typing.Optional[str]
            UUID based cursor, used for pagination. Should be the UUID of the last item in the previous page.

            Deprecated: prefer Cursor, the opaque cursor returned via the Zep-Next-Cursor response header.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ThreadSummary]
            Thread summaries

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.graph.thread_summary.get_by_graph_id(
                graph_id="graph_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_by_graph_id(
            graph_id,
            cursor=cursor,
            direction=direction,
            filters=filters,
            limit=limit,
            order_by=order_by,
            uuid_cursor=uuid_cursor,
            request_options=request_options,
        )
        return _response.data

    async def get_by_user_id(
        self,
        user_id: str,
        *,
        cursor: typing.Optional[str] = OMIT,
        direction: typing.Optional[str] = OMIT,
        filters: typing.Optional[SearchFilters] = OMIT,
        limit: typing.Optional[int] = OMIT,
        order_by: typing.Optional[str] = OMIT,
        uuid_cursor: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[ThreadSummary]:
        """
        Returns incremental thread summaries generated from messages in each thread associated with the user's graph.

        Parameters
        ----------
        user_id : str
            User ID

        cursor : typing.Optional[str]
            Opaque cursor for pagination, obtained from the Zep-Next-Cursor response header
            of the previous page. Encodes the sort field, direction, and continuation position.

        direction : typing.Optional[str]
            Sort direction. One of "asc" or "desc" (default "desc").

        filters : typing.Optional[SearchFilters]
            Optional filters applied to the listed artifacts. Reuses the graph.search filter type.

        limit : typing.Optional[int]
            Maximum number of items to return

        order_by : typing.Optional[str]
            Field to sort by. One of "created_at" or "uuid" (default "uuid").

        uuid_cursor : typing.Optional[str]
            UUID based cursor, used for pagination. Should be the UUID of the last item in the previous page.

            Deprecated: prefer Cursor, the opaque cursor returned via the Zep-Next-Cursor response header.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ThreadSummary]
            Thread summaries

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.graph.thread_summary.get_by_user_id(
                user_id="user_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_by_user_id(
            user_id,
            cursor=cursor,
            direction=direction,
            filters=filters,
            limit=limit,
            order_by=order_by,
            uuid_cursor=uuid_cursor,
            request_options=request_options,
        )
        return _response.data
