# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pagination import AsyncPager, SyncPager
from ..core.request_options import RequestOptions
from ..types.membership_mutation_result import MembershipMutationResult
from ..types.user import User
from ..types.user_group import UserGroup
from ..types.user_group_page import UserGroupPage
from ..types.user_page import UserPage
from .raw_client import AsyncRawUserGroupClient, RawUserGroupClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class UserGroupClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawUserGroupClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawUserGroupClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawUserGroupClient
        """
        return self._raw_client

    def create(
        self,
        *,
        name: str,
        description: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UserGroup:
        """
        Requires a project API key, or an account-admin bearer token with the X-Zep-Project header. The account must be entitled to attribute-based access control.

        Parameters
        ----------
        name : str
            The name of the user group.

        description : typing.Optional[str]
            A description of the user group.

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UserGroup
            Created

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        client.user_group.create(
            name="name",
        )
        """
        _response = self._raw_client.create(
            name=name, description=description, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    def list(
        self,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        search: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[UserGroup, UserGroupPage]:
        """
        Requires a project API key, or an account-admin bearer token with the X-Zep-Project header. The account must be entitled to attribute-based access control.

        Parameters
        ----------
        limit : typing.Optional[int]
            Page size

        cursor : typing.Optional[str]
            Opaque page cursor

        search : typing.Optional[str]
            Filters results to items matching this free-text search term.

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[UserGroup, UserGroupPage]
            OK

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        response = client.user_group.list(
            limit=1,
            cursor="cursor",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list(
            limit=limit, cursor=cursor, search=search, idempotency_key=idempotency_key, request_options=request_options
        )

    def get(self, group_uuid: str, *, request_options: typing.Optional[RequestOptions] = None) -> UserGroup:
        """
        Requires a project API key, or an account-admin bearer token with the X-Zep-Project header. The account must be entitled to attribute-based access control.

        Parameters
        ----------
        group_uuid : str
            User group UUID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UserGroup
            OK

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        client.user_group.get(
            group_uuid="group_uuid",
        )
        """
        _response = self._raw_client.get(group_uuid, request_options=request_options)
        return _response.data

    def delete(
        self,
        group_uuid: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Requires a project API key, or an account-admin bearer token with the X-Zep-Project header. The account must be entitled to attribute-based access control.

        Parameters
        ----------
        group_uuid : str
            User group UUID

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        client.user_group.delete(
            group_uuid="group_uuid",
        )
        """
        _response = self._raw_client.delete(
            group_uuid, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    def update(
        self,
        group_uuid: str,
        *,
        description: typing.Optional[str] = OMIT,
        expected_version: typing.Optional[int] = OMIT,
        name: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UserGroup:
        """
        Requires a project API key, or an account-admin bearer token with the X-Zep-Project header. The account must be entitled to attribute-based access control.

        Parameters
        ----------
        group_uuid : str
            User group UUID

        description : typing.Optional[str]
            A description of the user group.

        expected_version : typing.Optional[int]
            The user group's current version, used to detect concurrent updates.

        name : typing.Optional[str]
            The name of the user group.

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UserGroup
            OK

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        client.user_group.update(
            group_uuid="group_uuid",
        )
        """
        _response = self._raw_client.update(
            group_uuid,
            description=description,
            expected_version=expected_version,
            name=name,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    def list_member_candidates(
        self,
        group_uuid: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        search: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[User, UserPage]:
        """
        Requires a project API key, or an account-admin bearer token with the X-Zep-Project header. The account must be entitled to attribute-based access control.

        Parameters
        ----------
        group_uuid : str
            User group UUID

        limit : typing.Optional[int]
            Page size

        cursor : typing.Optional[str]
            Opaque page cursor

        search : typing.Optional[str]
            Filters results to items matching this free-text search term.

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[User, UserPage]
            OK

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        response = client.user_group.list_member_candidates(
            group_uuid="group_uuid",
            limit=1,
            cursor="cursor",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list_member_candidates(
            group_uuid,
            limit=limit,
            cursor=cursor,
            search=search,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )

    def add_members(
        self,
        group_uuid: str,
        *,
        user_uuids: typing.Sequence[str],
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MembershipMutationResult:
        """
        Requires a project API key, or an account-admin bearer token with the X-Zep-Project header. The account must be entitled to attribute-based access control.

        Parameters
        ----------
        group_uuid : str
            User group UUID

        user_uuids : typing.Sequence[str]
            The UUIDs of the users to add or remove.

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MembershipMutationResult
            OK

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        client.user_group.add_members(
            group_uuid="group_uuid",
            user_uuids=["user_uuids"],
        )
        """
        _response = self._raw_client.add_members(
            group_uuid, user_uuids=user_uuids, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    def list_members(
        self,
        group_uuid: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        search: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[User, UserPage]:
        """
        Requires a project API key, or an account-admin bearer token with the X-Zep-Project header. The account must be entitled to attribute-based access control.

        Parameters
        ----------
        group_uuid : str
            User group UUID

        limit : typing.Optional[int]
            Page size

        cursor : typing.Optional[str]
            Opaque page cursor

        search : typing.Optional[str]
            Filters results to items matching this free-text search term.

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[User, UserPage]
            OK

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        response = client.user_group.list_members(
            group_uuid="group_uuid",
            limit=1,
            cursor="cursor",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list_members(
            group_uuid,
            limit=limit,
            cursor=cursor,
            search=search,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )

    def remove_members(
        self,
        group_uuid: str,
        *,
        user_uuids: typing.Sequence[str],
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MembershipMutationResult:
        """
        Requires a project API key, or an account-admin bearer token with the X-Zep-Project header. The account must be entitled to attribute-based access control.

        Parameters
        ----------
        group_uuid : str
            User group UUID

        user_uuids : typing.Sequence[str]
            The UUIDs of the users to add or remove.

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MembershipMutationResult
            OK

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        client.user_group.remove_members(
            group_uuid="group_uuid",
            user_uuids=["user_uuids"],
        )
        """
        _response = self._raw_client.remove_members(
            group_uuid, user_uuids=user_uuids, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    def remove_member(
        self,
        group_uuid: str,
        user_uuid: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Requires a project API key, or an account-admin bearer token with the X-Zep-Project header. The account must be entitled to attribute-based access control.

        Parameters
        ----------
        group_uuid : str
            User group UUID

        user_uuid : str
            User UUID

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        client.user_group.remove_member(
            group_uuid="group_uuid",
            user_uuid="user_uuid",
        )
        """
        _response = self._raw_client.remove_member(
            group_uuid, user_uuid, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    def list_for_user(
        self,
        user_uuid: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[UserGroup, UserGroupPage]:
        """
        Requires a project API key, or an account-admin bearer token with the X-Zep-Project header. The account must be entitled to attribute-based access control.

        Parameters
        ----------
        user_uuid : str
            User UUID

        limit : typing.Optional[int]
            Page size

        cursor : typing.Optional[str]
            Opaque page cursor

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[UserGroup, UserGroupPage]
            OK

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        response = client.user_group.list_for_user(
            user_uuid="user_uuid",
            limit=1,
            cursor="cursor",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list_for_user(user_uuid, limit=limit, cursor=cursor, request_options=request_options)


class AsyncUserGroupClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawUserGroupClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawUserGroupClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawUserGroupClient
        """
        return self._raw_client

    async def create(
        self,
        *,
        name: str,
        description: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UserGroup:
        """
        Requires a project API key, or an account-admin bearer token with the X-Zep-Project header. The account must be entitled to attribute-based access control.

        Parameters
        ----------
        name : str
            The name of the user group.

        description : typing.Optional[str]
            A description of the user group.

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UserGroup
            Created

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.user_group.create(
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            name=name, description=description, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    async def list(
        self,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        search: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[UserGroup, UserGroupPage]:
        """
        Requires a project API key, or an account-admin bearer token with the X-Zep-Project header. The account must be entitled to attribute-based access control.

        Parameters
        ----------
        limit : typing.Optional[int]
            Page size

        cursor : typing.Optional[str]
            Opaque page cursor

        search : typing.Optional[str]
            Filters results to items matching this free-text search term.

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[UserGroup, UserGroupPage]
            OK

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.user_group.list(
                limit=1,
                cursor="cursor",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list(
            limit=limit, cursor=cursor, search=search, idempotency_key=idempotency_key, request_options=request_options
        )

    async def get(self, group_uuid: str, *, request_options: typing.Optional[RequestOptions] = None) -> UserGroup:
        """
        Requires a project API key, or an account-admin bearer token with the X-Zep-Project header. The account must be entitled to attribute-based access control.

        Parameters
        ----------
        group_uuid : str
            User group UUID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UserGroup
            OK

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.user_group.get(
                group_uuid="group_uuid",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(group_uuid, request_options=request_options)
        return _response.data

    async def delete(
        self,
        group_uuid: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Requires a project API key, or an account-admin bearer token with the X-Zep-Project header. The account must be entitled to attribute-based access control.

        Parameters
        ----------
        group_uuid : str
            User group UUID

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.user_group.delete(
                group_uuid="group_uuid",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(
            group_uuid, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    async def update(
        self,
        group_uuid: str,
        *,
        description: typing.Optional[str] = OMIT,
        expected_version: typing.Optional[int] = OMIT,
        name: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UserGroup:
        """
        Requires a project API key, or an account-admin bearer token with the X-Zep-Project header. The account must be entitled to attribute-based access control.

        Parameters
        ----------
        group_uuid : str
            User group UUID

        description : typing.Optional[str]
            A description of the user group.

        expected_version : typing.Optional[int]
            The user group's current version, used to detect concurrent updates.

        name : typing.Optional[str]
            The name of the user group.

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UserGroup
            OK

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.user_group.update(
                group_uuid="group_uuid",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            group_uuid,
            description=description,
            expected_version=expected_version,
            name=name,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    async def list_member_candidates(
        self,
        group_uuid: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        search: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[User, UserPage]:
        """
        Requires a project API key, or an account-admin bearer token with the X-Zep-Project header. The account must be entitled to attribute-based access control.

        Parameters
        ----------
        group_uuid : str
            User group UUID

        limit : typing.Optional[int]
            Page size

        cursor : typing.Optional[str]
            Opaque page cursor

        search : typing.Optional[str]
            Filters results to items matching this free-text search term.

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[User, UserPage]
            OK

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.user_group.list_member_candidates(
                group_uuid="group_uuid",
                limit=1,
                cursor="cursor",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list_member_candidates(
            group_uuid,
            limit=limit,
            cursor=cursor,
            search=search,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )

    async def add_members(
        self,
        group_uuid: str,
        *,
        user_uuids: typing.Sequence[str],
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MembershipMutationResult:
        """
        Requires a project API key, or an account-admin bearer token with the X-Zep-Project header. The account must be entitled to attribute-based access control.

        Parameters
        ----------
        group_uuid : str
            User group UUID

        user_uuids : typing.Sequence[str]
            The UUIDs of the users to add or remove.

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MembershipMutationResult
            OK

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.user_group.add_members(
                group_uuid="group_uuid",
                user_uuids=["user_uuids"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.add_members(
            group_uuid, user_uuids=user_uuids, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    async def list_members(
        self,
        group_uuid: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        search: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[User, UserPage]:
        """
        Requires a project API key, or an account-admin bearer token with the X-Zep-Project header. The account must be entitled to attribute-based access control.

        Parameters
        ----------
        group_uuid : str
            User group UUID

        limit : typing.Optional[int]
            Page size

        cursor : typing.Optional[str]
            Opaque page cursor

        search : typing.Optional[str]
            Filters results to items matching this free-text search term.

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[User, UserPage]
            OK

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.user_group.list_members(
                group_uuid="group_uuid",
                limit=1,
                cursor="cursor",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list_members(
            group_uuid,
            limit=limit,
            cursor=cursor,
            search=search,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )

    async def remove_members(
        self,
        group_uuid: str,
        *,
        user_uuids: typing.Sequence[str],
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MembershipMutationResult:
        """
        Requires a project API key, or an account-admin bearer token with the X-Zep-Project header. The account must be entitled to attribute-based access control.

        Parameters
        ----------
        group_uuid : str
            User group UUID

        user_uuids : typing.Sequence[str]
            The UUIDs of the users to add or remove.

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MembershipMutationResult
            OK

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.user_group.remove_members(
                group_uuid="group_uuid",
                user_uuids=["user_uuids"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.remove_members(
            group_uuid, user_uuids=user_uuids, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    async def remove_member(
        self,
        group_uuid: str,
        user_uuid: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Requires a project API key, or an account-admin bearer token with the X-Zep-Project header. The account must be entitled to attribute-based access control.

        Parameters
        ----------
        group_uuid : str
            User group UUID

        user_uuid : str
            User UUID

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.user_group.remove_member(
                group_uuid="group_uuid",
                user_uuid="user_uuid",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.remove_member(
            group_uuid, user_uuid, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    async def list_for_user(
        self,
        user_uuid: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[UserGroup, UserGroupPage]:
        """
        Requires a project API key, or an account-admin bearer token with the X-Zep-Project header. The account must be entitled to attribute-based access control.

        Parameters
        ----------
        user_uuid : str
            User UUID

        limit : typing.Optional[int]
            Page size

        cursor : typing.Optional[str]
            Opaque page cursor

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[UserGroup, UserGroupPage]
            OK

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.user_group.list_for_user(
                user_uuid="user_uuid",
                limit=1,
                cursor="cursor",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list_for_user(
            user_uuid, limit=limit, cursor=cursor, request_options=request_options
        )
