# This file was auto-generated by Fern from our API Definition.

import typing

CreateAgentSkillUseRequestUsage = typing.Union[
    typing.Literal["selected", "used", "partially_used", "ignored", "inapplicable"], typing.Any
]
