# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_verification_strength import AgentVerificationStrength


class AgentVerifierPrincipalBindingInput(UniversalBaseModel):
    effective_strength: AgentVerificationStrength = pydantic.Field()
    """
    The verification strength assigned to this principal binding.
    """

    principal_id: str = pydantic.Field()
    """
    The exact principal identifier. Wildcards are not supported.
    """

    principal_type: str = pydantic.Field()
    """
    The authenticated principal type: member, project-api-key, service, or mcp_user.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
