# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_context_evidence_counts import AgentContextEvidenceCounts


class AgentContextSkillSnapshot(UniversalBaseModel):
    artifact_sha256: typing.Optional[str] = None
    evidence_citations: typing.Optional[typing.List[str]] = None
    evidence_counts: typing.Optional[AgentContextEvidenceCounts] = None
    rank: typing.Optional[int] = None
    skill_uuid: typing.Optional[str] = None
    version: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
