# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .agent_skill_candidate_base_version import AgentSkillCandidateBaseVersion
from .agent_skill_candidate_evidence import AgentSkillCandidateEvidence


class AgentSkillCandidate(UniversalBaseModel):
    agent_versions: typing.Optional[typing.List[str]] = None
    base_versions: typing.Optional[typing.List[AgentSkillCandidateBaseVersion]] = None
    confidence: typing.Optional[float] = None
    decision: typing.Optional[str] = None
    description: typing.Optional[str] = None
    do_not_use_when: typing.Optional[typing.List[str]] = None
    evidence: typing.Optional[typing.List[AgentSkillCandidateEvidence]] = None
    kind: typing.Optional[str] = None
    markdown: typing.Optional[str] = None
    name: typing.Optional[str] = None
    package_name: typing.Optional[str] = None
    task_family: typing.Optional[str] = None
    uuid_: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="uuid"), pydantic.Field(alias="uuid")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
