# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .content_policy_event import ContentPolicyEvent


class ContentPolicyEventPage(UniversalBaseModel):
    items: typing.Optional[typing.List[ContentPolicyEvent]] = pydantic.Field(default=None)
    """
    The events on this page, newest first.
    """

    next_cursor: typing.Optional[str] = pydantic.Field(default=None)
    """
    The cursor to pass as the next request's cursor to fetch the following
    page; absent when no further pages remain.
    """

    total_size: typing.Optional[int] = pydantic.Field(default=None)
    """
    The total number of events that match the filters.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
