# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class ContextEdge(UniversalBaseModel):
    attributes: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Additional attributes of the edge.
    """

    created_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    The time the edge was created.
    """

    episode_uuids: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    The episodes this edge was derived from.
    """

    expired_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    The time the fact was superseded or removed.
    """

    fact: typing.Optional[str] = pydantic.Field(default=None)
    """
    The natural-language fact this edge represents.
    """

    graph_uuid: typing.Optional[str] = pydantic.Field(default=None)
    """
    The unique identifier of the graph this edge belongs to.
    """

    invalid_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    The time at which the fact stopped being true.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the edge, in upper snake case, for example RELATES_TO.
    """

    relevance: typing.Optional[float] = pydantic.Field(default=None)
    """
    A cross-encoder-derived relevance score, present only when the
    cross-encoder reranker scored this result; like score, it is omitted from
    plain list results.
    """

    scope: typing.Optional[str] = pydantic.Field(default=None)
    """
    The kind of edge this is, for example entity or episodic.
    """

    score: typing.Optional[float] = pydantic.Field(default=None)
    """
    The ranking score returned with every search result; omitted when the edge
    appears in a plain list rather than a search result.
    """

    selection_rank: typing.Optional[int] = pydantic.Field(default=None)
    """
    The 1-based position this edge was selected in across all context-assembly
    scopes.
    """

    source_node_labels: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    The current labels of the source node. This is read at request time rather
    than stored on the edge, and is omitted when the source node cannot be
    resolved.
    """

    source_node_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The current name of the source node. This is read at request time rather
    than stored on the edge, and is omitted when the source node cannot be
    resolved.
    """

    source_node_uuid: typing.Optional[str] = pydantic.Field(default=None)
    """
    The unique identifier of the edge's source node.
    """

    target_node_labels: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    The current labels of the target node. This is read at request time rather
    than stored on the edge, and is omitted when the target node cannot be
    resolved.
    """

    target_node_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The current name of the target node. This is read at request time rather
    than stored on the edge, and is omitted when the target node cannot be
    resolved.
    """

    target_node_uuid: typing.Optional[str] = pydantic.Field(default=None)
    """
    The unique identifier of the edge's target node.
    """

    uuid_: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="uuid"),
        pydantic.Field(alias="uuid", description="The unique identifier of the edge."),
    ] = None
    valid_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    The time from which the fact is considered true.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
