# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .date_filter_field import DateFilterField
from .date_filter_operator import DateFilterOperator


class DateFilter(UniversalBaseModel):
    field: typing.Optional[DateFilterField] = pydantic.Field(default=None)
    """
    The temporal field to compare.
    """

    operator: typing.Optional[DateFilterOperator] = pydantic.Field(default=None)
    """
    The lowercase comparison operator.
    """

    value: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The RFC 3339 timestamp. Omit this field for null operators.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
