# This file was auto-generated by Fern from our API Definition.

import typing

DateFilterOperator = typing.Union[
    typing.Literal["eq", "ne", "gt", "lt", "gte", "lte", "is_null", "is_not_null"], typing.Any
]
