# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .cluster_detect_config import ClusterDetectConfig
from .co_occurrence_detect_config import CoOccurrenceDetectConfig
from .hub_detect_config import HubDetectConfig
from .path_detect_config import PathDetectConfig
from .relationship_detect_config import RelationshipDetectConfig


class DetectConfig(UniversalBaseModel):
    clusters: typing.Optional[ClusterDetectConfig] = pydantic.Field(default=None)
    """
    Detect tightly interconnected groups (triangle topology)
    """

    co_occurrences: typing.Optional[CoOccurrenceDetectConfig] = pydantic.Field(default=None)
    """
    Detect node types that co-occur within k hops
    """

    hubs: typing.Optional[HubDetectConfig] = pydantic.Field(default=None)
    """
    Detect highly connected hub nodes (star topology)
    """

    paths: typing.Optional[PathDetectConfig] = pydantic.Field(default=None)
    """
    Detect frequent multi-hop connection paths
    """

    relationships: typing.Optional[RelationshipDetectConfig] = pydantic.Field(default=None)
    """
    Detect common (source_label, edge_type, target_label) relationship triples
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
