# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .entity_property_type import EntityPropertyType


class EntityProperty(UniversalBaseModel):
    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    A description of the property, used to guide extraction.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the property.
    """

    type: typing.Optional[EntityPropertyType] = pydantic.Field(default=None)
    """
    The value type of the property: text, int, float, or boolean.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
