# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class GraphEpisodeListRequest(UniversalBaseModel):
    cursor: typing.Optional[str] = pydantic.Field(default=None)
    """
    Opaque cursor for pagination, obtained from the Zep-Next-Cursor
    response header of the previous page.
    """

    direction: typing.Optional[str] = pydantic.Field(default=None)
    """
    Sort direction. One of "asc" or "desc". Defaults to "desc".
    """

    limit: typing.Optional[int] = pydantic.Field(default=None)
    """
    Maximum number of episodes to return. An explicit value is clamped to
    50; when omitted, the default page size (100) applies.
    """

    mentioned_node_uuids: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Restricts results to episodes that mention any of the listed node
    UUIDs. At most 256 entries; each must be a syntactically valid UUID.
    """

    order_by: typing.Optional[str] = pydantic.Field(default=None)
    """
    Field to sort by. One of "uuid" or "created_at". Defaults to "uuid".
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
