# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .ingestion_trace_edge import IngestionTraceEdge
from .ingestion_trace_edge_invalidation import IngestionTraceEdgeInvalidation
from .ingestion_trace_node import IngestionTraceNode
from .ingestion_trace_node_duplicate import IngestionTraceNodeDuplicate
from .ingestion_trace_node_resolution import IngestionTraceNodeResolution


class IngestionTraceOutput(UniversalBaseModel):
    edge_invalidations: typing.Optional[typing.List[IngestionTraceEdgeInvalidation]] = pydantic.Field(default=None)
    """
    The existing edges that the resolved edges invalidated. Present for resolve_edges and empty for
    the other steps.
    """

    edges: typing.Optional[typing.List[IngestionTraceEdge]] = pydantic.Field(default=None)
    """
    The resolved edges. Present for resolve_edges and empty for
    the other steps.
    """

    extracted_edges: typing.Optional[typing.List[IngestionTraceEdge]] = pydantic.Field(default=None)
    """
    The edges that the step extracted. Present for combined_extraction and
    empty for the other steps.
    """

    extracted_nodes: typing.Optional[typing.List[IngestionTraceNode]] = pydantic.Field(default=None)
    """
    The nodes that the step extracted. Present for combined_extraction and
    empty for the other steps.
    """

    new_edges: typing.Optional[typing.List[IngestionTraceEdge]] = pydantic.Field(default=None)
    """
    The resolved edges that are new to the graph. Present for resolve_edges and empty for
    the other steps.
    """

    node_duplicates: typing.Optional[typing.List[IngestionTraceNodeDuplicate]] = pydantic.Field(default=None)
    """
    The extracted nodes that the step found to be duplicates of existing
    nodes. Present for resolve_nodes and empty for
    the other steps.
    """

    node_resolutions: typing.Optional[typing.List[IngestionTraceNodeResolution]] = pydantic.Field(default=None)
    """
    The resolved node of each extracted node. Present for resolve_nodes and empty for
    the other steps.
    """

    nodes: typing.Optional[typing.List[IngestionTraceNode]] = pydantic.Field(default=None)
    """
    The resolved nodes. Present for resolve_nodes and empty for
    the other steps.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
