# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class IngestionTraceEdge(UniversalBaseModel):
    attributes: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Additional attributes of the edge, as defined by its edge type.
    """

    created_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    The time the edge was created.
    """

    episode_uuids: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    The episodes that the edge was derived from.
    """

    expired_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    The time the edge was superseded.
    """

    explanation: typing.Optional[str] = pydantic.Field(default=None)
    """
    The explanation of the decision of the step for this edge. Present only
    on output entries that have an explanation.
    """

    fact: typing.Optional[str] = pydantic.Field(default=None)
    """
    The natural-language fact that the edge represents.
    """

    invalid_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    The time at which the fact stopped being true.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the edge, in upper snake case.
    """

    source_node_uuid: typing.Optional[str] = pydantic.Field(default=None)
    """
    The unique identifier of the source node of the edge.
    """

    target_node_uuid: typing.Optional[str] = pydantic.Field(default=None)
    """
    The unique identifier of the target node of the edge.
    """

    uuid_: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="uuid"),
        pydantic.Field(alias="uuid", description="The unique identifier of the edge."),
    ] = None
    """
    The unique identifier of the edge.
    """

    valid_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    The time from which the fact is true.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
