# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .lookup_item import LookupItem


class LookupBatchResponse(UniversalBaseModel):
    items: typing.Optional[typing.List[LookupItem]] = pydantic.Field(default=None)
    """
    The lookup result for each identifier submitted, in request order within
    each resource type.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
