# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .thread import Thread


class ThreadPage(UniversalBaseModel):
    items: typing.Optional[typing.List[Thread]] = pydantic.Field(default=None)
    """
    The threads on this page.
    """

    next_cursor: typing.Optional[str] = pydantic.Field(default=None)
    """
    The cursor to pass as the next request's cursor to fetch the following
    page; absent when no further pages remain.
    """

    total_size: typing.Optional[int] = pydantic.Field(default=None)
    """
    The total number of matching threads, counted at the time of this
    response. It does not indicate whether more pages remain.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
