# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .trace_score_range import TraceScoreRange


class TraceFilter(UniversalBaseModel):
    has_error: typing.Optional[bool] = pydantic.Field(default=None)
    """
    HasError filters traces by their error state.
    """

    metadata: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Metadata contains exact-match root metadata filters. Example: {"team":"support"}.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name is the exact trace name filter.
    """

    scores: typing.Optional[typing.List[TraceScoreRange]] = pydantic.Field(default=None)
    """
    Scores contains score name and range filters. Example: [{"name":"quality","min":0.5}].
    """

    started_after: typing.Optional[str] = pydantic.Field(default=None)
    """
    StartedAfter is the inclusive trace start-time lower bound.
    """

    started_before: typing.Optional[str] = pydantic.Field(default=None)
    """
    StartedBefore is the exclusive trace start-time upper bound.
    """

    tags_all: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    TagsAll contains tags that every result must include.
    """

    tags_any: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    TagsAny contains tags that at least one result must include.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
