# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pagination import AsyncPager, SyncPager
from ..core.request_options import RequestOptions
from ..types.async_result import AsyncResult
from ..types.clone_graph_result import CloneGraphResult
from ..types.edge import Edge
from ..types.edge_page import EdgePage
from ..types.edge_type import EdgeType
from ..types.entity_type import EntityType
from ..types.episode import Episode
from ..types.episode_page import EpisodePage
from ..types.graph import Graph
from ..types.graph_context_response import GraphContextResponse
from ..types.graph_delete_result import GraphDeleteResult
from ..types.graph_page import GraphPage
from ..types.instructions import Instructions
from ..types.node import Node
from ..types.node_page import NodePage
from ..types.observation import Observation
from ..types.observation_page import ObservationPage
from ..types.observation_steering import ObservationSteering
from ..types.ontology import Ontology
from ..types.subgraph_response import SubgraphResponse
from ..types.thread_summary import ThreadSummary
from ..types.thread_summary_page import ThreadSummaryPage
from .raw_client import AsyncRawGraphClient, RawGraphClient

if typing.TYPE_CHECKING:
    from .document_summary.client import AsyncDocumentSummaryClient, DocumentSummaryClient
    from .edge.client import AsyncEdgeClient, EdgeClient
    from .episode.client import AsyncEpisodeClient, EpisodeClient
    from .node.client import AsyncNodeClient, NodeClient
    from .observation.client import AsyncObservationClient, ObservationClient
    from .thread_summary.client import AsyncThreadSummaryClient, ThreadSummaryClient
# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class GraphClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawGraphClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._document_summary: typing.Optional[DocumentSummaryClient] = None
        self._episode: typing.Optional[EpisodeClient] = None
        self._edge: typing.Optional[EdgeClient] = None
        self._node: typing.Optional[NodeClient] = None
        self._observation: typing.Optional[ObservationClient] = None
        self._thread_summary: typing.Optional[ThreadSummaryClient] = None

    @property
    def with_raw_response(self) -> RawGraphClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawGraphClient
        """
        return self._raw_client

    def create(
        self,
        *,
        description: typing.Optional[str] = OMIT,
        graph_id: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        time_zone: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Graph:
        """
        Parameters
        ----------
        description : typing.Optional[str]

        graph_id : typing.Optional[str]

        name : typing.Optional[str]

        time_zone : typing.Optional[str]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Graph
            Created

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        client.graph.create()
        """
        _response = self._raw_client.create(
            description=description,
            graph_id=graph_id,
            name=name,
            time_zone=time_zone,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    def list(
        self,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        order_by: typing.Optional[str] = None,
        order: typing.Optional[str] = None,
        search: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[Graph, GraphPage]:
        """
        Parameters
        ----------
        limit : typing.Optional[int]
            Page size

        cursor : typing.Optional[str]
            Opaque page cursor

        order_by : typing.Optional[str]
            Sort field

        order : typing.Optional[str]
            asc or desc

        search : typing.Optional[str]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[Graph, GraphPage]
            OK

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        response = client.graph.list(
            limit=1,
            cursor="cursor",
            order_by="order_by",
            order="order",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list(
            limit=limit,
            cursor=cursor,
            order_by=order_by,
            order=order,
            search=search,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )

    def lookup(
        self,
        *,
        graph_id: typing.Optional[str] = OMIT,
        thread_id: typing.Optional[str] = OMIT,
        user_id: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Graph:
        """
        Parameters
        ----------
        graph_id : typing.Optional[str]

        thread_id : typing.Optional[str]

        user_id : typing.Optional[str]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Graph
            OK

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        client.graph.lookup()
        """
        _response = self._raw_client.lookup(
            graph_id=graph_id,
            thread_id=thread_id,
            user_id=user_id,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    def get(self, graph_uuid: str, *, request_options: typing.Optional[RequestOptions] = None) -> Graph:
        """
        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Graph
            OK

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        client.graph.get(
            graph_uuid="graph_uuid",
        )
        """
        _response = self._raw_client.get(graph_uuid, request_options=request_options)
        return _response.data

    def delete(
        self,
        graph_uuid: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GraphDeleteResult:
        """
        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GraphDeleteResult
            Accepted

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        client.graph.delete(
            graph_uuid="graph_uuid",
        )
        """
        _response = self._raw_client.delete(
            graph_uuid, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    def update(
        self,
        graph_uuid: str,
        *,
        description: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        time_zone: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Graph:
        """
        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        description : typing.Optional[str]
            Omit to leave unchanged, send JSON null to clear, or send a value to set.

        name : typing.Optional[str]
            Omit to leave unchanged, send JSON null to clear, or send a value to set.

        time_zone : typing.Optional[str]
            Omit to leave unchanged, send JSON null to clear, or send a value to set.

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Graph
            OK

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        client.graph.update(
            graph_uuid="graph_uuid",
        )
        """
        _response = self._raw_client.update(
            graph_uuid,
            description=description,
            name=name,
            time_zone=time_zone,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    def clone(
        self,
        graph_uuid: str,
        *,
        target_graph_id: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CloneGraphResult:
        """
        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        target_graph_id : typing.Optional[str]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CloneGraphResult
            Accepted

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        client.graph.clone(
            graph_uuid="graph_uuid",
        )
        """
        _response = self._raw_client.clone(
            graph_uuid,
            target_graph_id=target_graph_id,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    def get_context(
        self,
        graph_uuid: str,
        *,
        filters: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        include_results: typing.Optional[bool] = OMIT,
        max_characters: typing.Optional[int] = OMIT,
        query: typing.Optional[str] = OMIT,
        recency_bias: typing.Optional[str] = OMIT,
        template_uuid: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GraphContextResponse:
        """
        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        filters : typing.Optional[typing.Dict[str, typing.Any]]

        include_results : typing.Optional[bool]

        max_characters : typing.Optional[int]

        query : typing.Optional[str]

        recency_bias : typing.Optional[str]

        template_uuid : typing.Optional[str]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GraphContextResponse
            OK

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        client.graph.get_context(
            graph_uuid="graph_uuid",
        )
        """
        _response = self._raw_client.get_context(
            graph_uuid,
            filters=filters,
            include_results=include_results,
            max_characters=max_characters,
            query=query,
            recency_bias=recency_bias,
            template_uuid=template_uuid,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    def get_instructions(
        self, graph_uuid: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> Instructions:
        """
        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Instructions
            OK

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        client.graph.get_instructions(
            graph_uuid="graph_uuid",
        )
        """
        _response = self._raw_client.get_instructions(graph_uuid, request_options=request_options)
        return _response.data

    def set_instructions(
        self,
        graph_uuid: str,
        *,
        inherited: typing.Optional[bool] = OMIT,
        instructions: typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Instructions:
        """
        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        inherited : typing.Optional[bool]

        instructions : typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Instructions
            OK

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        client.graph.set_instructions(
            graph_uuid="graph_uuid",
        )
        """
        _response = self._raw_client.set_instructions(
            graph_uuid,
            inherited=inherited,
            instructions=instructions,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    def get_observation_steering(
        self, graph_uuid: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ObservationSteering:
        """
        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ObservationSteering
            OK

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        client.graph.get_observation_steering(
            graph_uuid="graph_uuid",
        )
        """
        _response = self._raw_client.get_observation_steering(graph_uuid, request_options=request_options)
        return _response.data

    def set_observation_steering(
        self,
        graph_uuid: str,
        *,
        inherited: typing.Optional[bool] = OMIT,
        instruction: typing.Optional[str] = OMIT,
        types: typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ObservationSteering:
        """
        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        inherited : typing.Optional[bool]

        instruction : typing.Optional[str]

        types : typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ObservationSteering
            OK

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        client.graph.set_observation_steering(
            graph_uuid="graph_uuid",
        )
        """
        _response = self._raw_client.set_observation_steering(
            graph_uuid,
            inherited=inherited,
            instruction=instruction,
            types=types,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    def get_ontology(self, graph_uuid: str, *, request_options: typing.Optional[RequestOptions] = None) -> Ontology:
        """
        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Ontology
            OK

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        client.graph.get_ontology(
            graph_uuid="graph_uuid",
        )
        """
        _response = self._raw_client.get_ontology(graph_uuid, request_options=request_options)
        return _response.data

    def set_ontology(
        self,
        graph_uuid: str,
        *,
        edge_types: typing.Optional[typing.Sequence[EdgeType]] = OMIT,
        entity_types: typing.Optional[typing.Sequence[EntityType]] = OMIT,
        inherited: typing.Optional[bool] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Ontology:
        """
        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        edge_types : typing.Optional[typing.Sequence[EdgeType]]

        entity_types : typing.Optional[typing.Sequence[EntityType]]

        inherited : typing.Optional[bool]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Ontology
            OK

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        client.graph.set_ontology(
            graph_uuid="graph_uuid",
        )
        """
        _response = self._raw_client.set_ontology(
            graph_uuid,
            edge_types=edge_types,
            entity_types=entity_types,
            inherited=inherited,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    def search_edges(
        self,
        graph_uuid: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        bfs_origin_node_uuids: typing.Optional[typing.Sequence[str]] = OMIT,
        center_node_uuid: typing.Optional[str] = OMIT,
        filters: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        mmr_lambda: typing.Optional[float] = OMIT,
        query: typing.Optional[str] = OMIT,
        reranker: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[Edge, EdgePage]:
        """
        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        limit : typing.Optional[int]
            Page size

        cursor : typing.Optional[str]
            Opaque page cursor

        bfs_origin_node_uuids : typing.Optional[typing.Sequence[str]]

        center_node_uuid : typing.Optional[str]

        filters : typing.Optional[typing.Dict[str, typing.Any]]

        mmr_lambda : typing.Optional[float]

        query : typing.Optional[str]

        reranker : typing.Optional[str]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[Edge, EdgePage]
            OK

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        response = client.graph.search_edges(
            graph_uuid="graph_uuid",
            limit=1,
            cursor="cursor",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.search_edges(
            graph_uuid,
            limit=limit,
            cursor=cursor,
            bfs_origin_node_uuids=bfs_origin_node_uuids,
            center_node_uuid=center_node_uuid,
            filters=filters,
            mmr_lambda=mmr_lambda,
            query=query,
            reranker=reranker,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )

    def search_episodes(
        self,
        graph_uuid: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        bfs_origin_node_uuids: typing.Optional[typing.Sequence[str]] = OMIT,
        center_node_uuid: typing.Optional[str] = OMIT,
        filters: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        mmr_lambda: typing.Optional[float] = OMIT,
        query: typing.Optional[str] = OMIT,
        reranker: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[Episode, EpisodePage]:
        """
        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        limit : typing.Optional[int]
            Page size

        cursor : typing.Optional[str]
            Opaque page cursor

        bfs_origin_node_uuids : typing.Optional[typing.Sequence[str]]

        center_node_uuid : typing.Optional[str]

        filters : typing.Optional[typing.Dict[str, typing.Any]]

        mmr_lambda : typing.Optional[float]

        query : typing.Optional[str]

        reranker : typing.Optional[str]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[Episode, EpisodePage]
            OK

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        response = client.graph.search_episodes(
            graph_uuid="graph_uuid",
            limit=1,
            cursor="cursor",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.search_episodes(
            graph_uuid,
            limit=limit,
            cursor=cursor,
            bfs_origin_node_uuids=bfs_origin_node_uuids,
            center_node_uuid=center_node_uuid,
            filters=filters,
            mmr_lambda=mmr_lambda,
            query=query,
            reranker=reranker,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )

    def search_nodes(
        self,
        graph_uuid: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        bfs_origin_node_uuids: typing.Optional[typing.Sequence[str]] = OMIT,
        center_node_uuid: typing.Optional[str] = OMIT,
        filters: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        mmr_lambda: typing.Optional[float] = OMIT,
        query: typing.Optional[str] = OMIT,
        reranker: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[Node, NodePage]:
        """
        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        limit : typing.Optional[int]
            Page size

        cursor : typing.Optional[str]
            Opaque page cursor

        bfs_origin_node_uuids : typing.Optional[typing.Sequence[str]]

        center_node_uuid : typing.Optional[str]

        filters : typing.Optional[typing.Dict[str, typing.Any]]

        mmr_lambda : typing.Optional[float]

        query : typing.Optional[str]

        reranker : typing.Optional[str]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[Node, NodePage]
            OK

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        response = client.graph.search_nodes(
            graph_uuid="graph_uuid",
            limit=1,
            cursor="cursor",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.search_nodes(
            graph_uuid,
            limit=limit,
            cursor=cursor,
            bfs_origin_node_uuids=bfs_origin_node_uuids,
            center_node_uuid=center_node_uuid,
            filters=filters,
            mmr_lambda=mmr_lambda,
            query=query,
            reranker=reranker,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )

    def search_observations(
        self,
        graph_uuid: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        bfs_origin_node_uuids: typing.Optional[typing.Sequence[str]] = OMIT,
        center_node_uuid: typing.Optional[str] = OMIT,
        filters: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        mmr_lambda: typing.Optional[float] = OMIT,
        query: typing.Optional[str] = OMIT,
        reranker: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[Observation, ObservationPage]:
        """
        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        limit : typing.Optional[int]
            Page size

        cursor : typing.Optional[str]
            Opaque page cursor

        bfs_origin_node_uuids : typing.Optional[typing.Sequence[str]]

        center_node_uuid : typing.Optional[str]

        filters : typing.Optional[typing.Dict[str, typing.Any]]

        mmr_lambda : typing.Optional[float]

        query : typing.Optional[str]

        reranker : typing.Optional[str]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[Observation, ObservationPage]
            OK

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        response = client.graph.search_observations(
            graph_uuid="graph_uuid",
            limit=1,
            cursor="cursor",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.search_observations(
            graph_uuid,
            limit=limit,
            cursor=cursor,
            bfs_origin_node_uuids=bfs_origin_node_uuids,
            center_node_uuid=center_node_uuid,
            filters=filters,
            mmr_lambda=mmr_lambda,
            query=query,
            reranker=reranker,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )

    def search_thread_summaries(
        self,
        graph_uuid: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        bfs_origin_node_uuids: typing.Optional[typing.Sequence[str]] = OMIT,
        center_node_uuid: typing.Optional[str] = OMIT,
        filters: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        mmr_lambda: typing.Optional[float] = OMIT,
        query: typing.Optional[str] = OMIT,
        reranker: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[ThreadSummary, ThreadSummaryPage]:
        """
        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        limit : typing.Optional[int]
            Page size

        cursor : typing.Optional[str]
            Opaque page cursor

        bfs_origin_node_uuids : typing.Optional[typing.Sequence[str]]

        center_node_uuid : typing.Optional[str]

        filters : typing.Optional[typing.Dict[str, typing.Any]]

        mmr_lambda : typing.Optional[float]

        query : typing.Optional[str]

        reranker : typing.Optional[str]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[ThreadSummary, ThreadSummaryPage]
            OK

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        response = client.graph.search_thread_summaries(
            graph_uuid="graph_uuid",
            limit=1,
            cursor="cursor",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.search_thread_summaries(
            graph_uuid,
            limit=limit,
            cursor=cursor,
            bfs_origin_node_uuids=bfs_origin_node_uuids,
            center_node_uuid=center_node_uuid,
            filters=filters,
            mmr_lambda=mmr_lambda,
            query=query,
            reranker=reranker,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )

    def get_subgraph(
        self,
        graph_uuid: str,
        *,
        depth: typing.Optional[int] = OMIT,
        direction: typing.Optional[str] = OMIT,
        filters: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        max_edges: typing.Optional[int] = OMIT,
        max_nodes: typing.Optional[int] = OMIT,
        seed_node_uuids: typing.Optional[typing.Sequence[str]] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SubgraphResponse:
        """
        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        depth : typing.Optional[int]

        direction : typing.Optional[str]

        filters : typing.Optional[typing.Dict[str, typing.Any]]

        max_edges : typing.Optional[int]

        max_nodes : typing.Optional[int]

        seed_node_uuids : typing.Optional[typing.Sequence[str]]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubgraphResponse
            OK

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        client.graph.get_subgraph(
            graph_uuid="graph_uuid",
        )
        """
        _response = self._raw_client.get_subgraph(
            graph_uuid,
            depth=depth,
            direction=direction,
            filters=filters,
            max_edges=max_edges,
            max_nodes=max_nodes,
            seed_node_uuids=seed_node_uuids,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    def warm(
        self,
        graph_uuid: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncResult:
        """
        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncResult
            Accepted

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        client.graph.warm(
            graph_uuid="graph_uuid",
        )
        """
        _response = self._raw_client.warm(graph_uuid, idempotency_key=idempotency_key, request_options=request_options)
        return _response.data

    @property
    def document_summary(self):
        if self._document_summary is None:
            from .document_summary.client import DocumentSummaryClient  # noqa: E402

            self._document_summary = DocumentSummaryClient(client_wrapper=self._client_wrapper)
        return self._document_summary

    @property
    def episode(self):
        if self._episode is None:
            from .episode.client import EpisodeClient  # noqa: E402

            self._episode = EpisodeClient(client_wrapper=self._client_wrapper)
        return self._episode

    @property
    def edge(self):
        if self._edge is None:
            from .edge.client import EdgeClient  # noqa: E402

            self._edge = EdgeClient(client_wrapper=self._client_wrapper)
        return self._edge

    @property
    def node(self):
        if self._node is None:
            from .node.client import NodeClient  # noqa: E402

            self._node = NodeClient(client_wrapper=self._client_wrapper)
        return self._node

    @property
    def observation(self):
        if self._observation is None:
            from .observation.client import ObservationClient  # noqa: E402

            self._observation = ObservationClient(client_wrapper=self._client_wrapper)
        return self._observation

    @property
    def thread_summary(self):
        if self._thread_summary is None:
            from .thread_summary.client import ThreadSummaryClient  # noqa: E402

            self._thread_summary = ThreadSummaryClient(client_wrapper=self._client_wrapper)
        return self._thread_summary


class AsyncGraphClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawGraphClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._document_summary: typing.Optional[AsyncDocumentSummaryClient] = None
        self._episode: typing.Optional[AsyncEpisodeClient] = None
        self._edge: typing.Optional[AsyncEdgeClient] = None
        self._node: typing.Optional[AsyncNodeClient] = None
        self._observation: typing.Optional[AsyncObservationClient] = None
        self._thread_summary: typing.Optional[AsyncThreadSummaryClient] = None

    @property
    def with_raw_response(self) -> AsyncRawGraphClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawGraphClient
        """
        return self._raw_client

    async def create(
        self,
        *,
        description: typing.Optional[str] = OMIT,
        graph_id: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        time_zone: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Graph:
        """
        Parameters
        ----------
        description : typing.Optional[str]

        graph_id : typing.Optional[str]

        name : typing.Optional[str]

        time_zone : typing.Optional[str]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Graph
            Created

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.graph.create()


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            description=description,
            graph_id=graph_id,
            name=name,
            time_zone=time_zone,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    async def list(
        self,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        order_by: typing.Optional[str] = None,
        order: typing.Optional[str] = None,
        search: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[Graph, GraphPage]:
        """
        Parameters
        ----------
        limit : typing.Optional[int]
            Page size

        cursor : typing.Optional[str]
            Opaque page cursor

        order_by : typing.Optional[str]
            Sort field

        order : typing.Optional[str]
            asc or desc

        search : typing.Optional[str]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[Graph, GraphPage]
            OK

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.graph.list(
                limit=1,
                cursor="cursor",
                order_by="order_by",
                order="order",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list(
            limit=limit,
            cursor=cursor,
            order_by=order_by,
            order=order,
            search=search,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )

    async def lookup(
        self,
        *,
        graph_id: typing.Optional[str] = OMIT,
        thread_id: typing.Optional[str] = OMIT,
        user_id: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Graph:
        """
        Parameters
        ----------
        graph_id : typing.Optional[str]

        thread_id : typing.Optional[str]

        user_id : typing.Optional[str]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Graph
            OK

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.graph.lookup()


        asyncio.run(main())
        """
        _response = await self._raw_client.lookup(
            graph_id=graph_id,
            thread_id=thread_id,
            user_id=user_id,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    async def get(self, graph_uuid: str, *, request_options: typing.Optional[RequestOptions] = None) -> Graph:
        """
        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Graph
            OK

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.graph.get(
                graph_uuid="graph_uuid",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(graph_uuid, request_options=request_options)
        return _response.data

    async def delete(
        self,
        graph_uuid: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GraphDeleteResult:
        """
        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GraphDeleteResult
            Accepted

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.graph.delete(
                graph_uuid="graph_uuid",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(
            graph_uuid, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    async def update(
        self,
        graph_uuid: str,
        *,
        description: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        time_zone: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Graph:
        """
        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        description : typing.Optional[str]
            Omit to leave unchanged, send JSON null to clear, or send a value to set.

        name : typing.Optional[str]
            Omit to leave unchanged, send JSON null to clear, or send a value to set.

        time_zone : typing.Optional[str]
            Omit to leave unchanged, send JSON null to clear, or send a value to set.

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Graph
            OK

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.graph.update(
                graph_uuid="graph_uuid",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            graph_uuid,
            description=description,
            name=name,
            time_zone=time_zone,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    async def clone(
        self,
        graph_uuid: str,
        *,
        target_graph_id: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CloneGraphResult:
        """
        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        target_graph_id : typing.Optional[str]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CloneGraphResult
            Accepted

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.graph.clone(
                graph_uuid="graph_uuid",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.clone(
            graph_uuid,
            target_graph_id=target_graph_id,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    async def get_context(
        self,
        graph_uuid: str,
        *,
        filters: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        include_results: typing.Optional[bool] = OMIT,
        max_characters: typing.Optional[int] = OMIT,
        query: typing.Optional[str] = OMIT,
        recency_bias: typing.Optional[str] = OMIT,
        template_uuid: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GraphContextResponse:
        """
        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        filters : typing.Optional[typing.Dict[str, typing.Any]]

        include_results : typing.Optional[bool]

        max_characters : typing.Optional[int]

        query : typing.Optional[str]

        recency_bias : typing.Optional[str]

        template_uuid : typing.Optional[str]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GraphContextResponse
            OK

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.graph.get_context(
                graph_uuid="graph_uuid",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_context(
            graph_uuid,
            filters=filters,
            include_results=include_results,
            max_characters=max_characters,
            query=query,
            recency_bias=recency_bias,
            template_uuid=template_uuid,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    async def get_instructions(
        self, graph_uuid: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> Instructions:
        """
        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Instructions
            OK

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.graph.get_instructions(
                graph_uuid="graph_uuid",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_instructions(graph_uuid, request_options=request_options)
        return _response.data

    async def set_instructions(
        self,
        graph_uuid: str,
        *,
        inherited: typing.Optional[bool] = OMIT,
        instructions: typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Instructions:
        """
        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        inherited : typing.Optional[bool]

        instructions : typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Instructions
            OK

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.graph.set_instructions(
                graph_uuid="graph_uuid",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.set_instructions(
            graph_uuid,
            inherited=inherited,
            instructions=instructions,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    async def get_observation_steering(
        self, graph_uuid: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ObservationSteering:
        """
        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ObservationSteering
            OK

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.graph.get_observation_steering(
                graph_uuid="graph_uuid",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_observation_steering(graph_uuid, request_options=request_options)
        return _response.data

    async def set_observation_steering(
        self,
        graph_uuid: str,
        *,
        inherited: typing.Optional[bool] = OMIT,
        instruction: typing.Optional[str] = OMIT,
        types: typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ObservationSteering:
        """
        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        inherited : typing.Optional[bool]

        instruction : typing.Optional[str]

        types : typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ObservationSteering
            OK

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.graph.set_observation_steering(
                graph_uuid="graph_uuid",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.set_observation_steering(
            graph_uuid,
            inherited=inherited,
            instruction=instruction,
            types=types,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    async def get_ontology(
        self, graph_uuid: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> Ontology:
        """
        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Ontology
            OK

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.graph.get_ontology(
                graph_uuid="graph_uuid",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_ontology(graph_uuid, request_options=request_options)
        return _response.data

    async def set_ontology(
        self,
        graph_uuid: str,
        *,
        edge_types: typing.Optional[typing.Sequence[EdgeType]] = OMIT,
        entity_types: typing.Optional[typing.Sequence[EntityType]] = OMIT,
        inherited: typing.Optional[bool] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Ontology:
        """
        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        edge_types : typing.Optional[typing.Sequence[EdgeType]]

        entity_types : typing.Optional[typing.Sequence[EntityType]]

        inherited : typing.Optional[bool]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Ontology
            OK

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.graph.set_ontology(
                graph_uuid="graph_uuid",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.set_ontology(
            graph_uuid,
            edge_types=edge_types,
            entity_types=entity_types,
            inherited=inherited,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    async def search_edges(
        self,
        graph_uuid: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        bfs_origin_node_uuids: typing.Optional[typing.Sequence[str]] = OMIT,
        center_node_uuid: typing.Optional[str] = OMIT,
        filters: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        mmr_lambda: typing.Optional[float] = OMIT,
        query: typing.Optional[str] = OMIT,
        reranker: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[Edge, EdgePage]:
        """
        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        limit : typing.Optional[int]
            Page size

        cursor : typing.Optional[str]
            Opaque page cursor

        bfs_origin_node_uuids : typing.Optional[typing.Sequence[str]]

        center_node_uuid : typing.Optional[str]

        filters : typing.Optional[typing.Dict[str, typing.Any]]

        mmr_lambda : typing.Optional[float]

        query : typing.Optional[str]

        reranker : typing.Optional[str]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[Edge, EdgePage]
            OK

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.graph.search_edges(
                graph_uuid="graph_uuid",
                limit=1,
                cursor="cursor",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.search_edges(
            graph_uuid,
            limit=limit,
            cursor=cursor,
            bfs_origin_node_uuids=bfs_origin_node_uuids,
            center_node_uuid=center_node_uuid,
            filters=filters,
            mmr_lambda=mmr_lambda,
            query=query,
            reranker=reranker,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )

    async def search_episodes(
        self,
        graph_uuid: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        bfs_origin_node_uuids: typing.Optional[typing.Sequence[str]] = OMIT,
        center_node_uuid: typing.Optional[str] = OMIT,
        filters: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        mmr_lambda: typing.Optional[float] = OMIT,
        query: typing.Optional[str] = OMIT,
        reranker: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[Episode, EpisodePage]:
        """
        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        limit : typing.Optional[int]
            Page size

        cursor : typing.Optional[str]
            Opaque page cursor

        bfs_origin_node_uuids : typing.Optional[typing.Sequence[str]]

        center_node_uuid : typing.Optional[str]

        filters : typing.Optional[typing.Dict[str, typing.Any]]

        mmr_lambda : typing.Optional[float]

        query : typing.Optional[str]

        reranker : typing.Optional[str]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[Episode, EpisodePage]
            OK

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.graph.search_episodes(
                graph_uuid="graph_uuid",
                limit=1,
                cursor="cursor",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.search_episodes(
            graph_uuid,
            limit=limit,
            cursor=cursor,
            bfs_origin_node_uuids=bfs_origin_node_uuids,
            center_node_uuid=center_node_uuid,
            filters=filters,
            mmr_lambda=mmr_lambda,
            query=query,
            reranker=reranker,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )

    async def search_nodes(
        self,
        graph_uuid: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        bfs_origin_node_uuids: typing.Optional[typing.Sequence[str]] = OMIT,
        center_node_uuid: typing.Optional[str] = OMIT,
        filters: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        mmr_lambda: typing.Optional[float] = OMIT,
        query: typing.Optional[str] = OMIT,
        reranker: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[Node, NodePage]:
        """
        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        limit : typing.Optional[int]
            Page size

        cursor : typing.Optional[str]
            Opaque page cursor

        bfs_origin_node_uuids : typing.Optional[typing.Sequence[str]]

        center_node_uuid : typing.Optional[str]

        filters : typing.Optional[typing.Dict[str, typing.Any]]

        mmr_lambda : typing.Optional[float]

        query : typing.Optional[str]

        reranker : typing.Optional[str]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[Node, NodePage]
            OK

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.graph.search_nodes(
                graph_uuid="graph_uuid",
                limit=1,
                cursor="cursor",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.search_nodes(
            graph_uuid,
            limit=limit,
            cursor=cursor,
            bfs_origin_node_uuids=bfs_origin_node_uuids,
            center_node_uuid=center_node_uuid,
            filters=filters,
            mmr_lambda=mmr_lambda,
            query=query,
            reranker=reranker,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )

    async def search_observations(
        self,
        graph_uuid: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        bfs_origin_node_uuids: typing.Optional[typing.Sequence[str]] = OMIT,
        center_node_uuid: typing.Optional[str] = OMIT,
        filters: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        mmr_lambda: typing.Optional[float] = OMIT,
        query: typing.Optional[str] = OMIT,
        reranker: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[Observation, ObservationPage]:
        """
        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        limit : typing.Optional[int]
            Page size

        cursor : typing.Optional[str]
            Opaque page cursor

        bfs_origin_node_uuids : typing.Optional[typing.Sequence[str]]

        center_node_uuid : typing.Optional[str]

        filters : typing.Optional[typing.Dict[str, typing.Any]]

        mmr_lambda : typing.Optional[float]

        query : typing.Optional[str]

        reranker : typing.Optional[str]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[Observation, ObservationPage]
            OK

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.graph.search_observations(
                graph_uuid="graph_uuid",
                limit=1,
                cursor="cursor",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.search_observations(
            graph_uuid,
            limit=limit,
            cursor=cursor,
            bfs_origin_node_uuids=bfs_origin_node_uuids,
            center_node_uuid=center_node_uuid,
            filters=filters,
            mmr_lambda=mmr_lambda,
            query=query,
            reranker=reranker,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )

    async def search_thread_summaries(
        self,
        graph_uuid: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        bfs_origin_node_uuids: typing.Optional[typing.Sequence[str]] = OMIT,
        center_node_uuid: typing.Optional[str] = OMIT,
        filters: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        mmr_lambda: typing.Optional[float] = OMIT,
        query: typing.Optional[str] = OMIT,
        reranker: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[ThreadSummary, ThreadSummaryPage]:
        """
        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        limit : typing.Optional[int]
            Page size

        cursor : typing.Optional[str]
            Opaque page cursor

        bfs_origin_node_uuids : typing.Optional[typing.Sequence[str]]

        center_node_uuid : typing.Optional[str]

        filters : typing.Optional[typing.Dict[str, typing.Any]]

        mmr_lambda : typing.Optional[float]

        query : typing.Optional[str]

        reranker : typing.Optional[str]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[ThreadSummary, ThreadSummaryPage]
            OK

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.graph.search_thread_summaries(
                graph_uuid="graph_uuid",
                limit=1,
                cursor="cursor",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.search_thread_summaries(
            graph_uuid,
            limit=limit,
            cursor=cursor,
            bfs_origin_node_uuids=bfs_origin_node_uuids,
            center_node_uuid=center_node_uuid,
            filters=filters,
            mmr_lambda=mmr_lambda,
            query=query,
            reranker=reranker,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )

    async def get_subgraph(
        self,
        graph_uuid: str,
        *,
        depth: typing.Optional[int] = OMIT,
        direction: typing.Optional[str] = OMIT,
        filters: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        max_edges: typing.Optional[int] = OMIT,
        max_nodes: typing.Optional[int] = OMIT,
        seed_node_uuids: typing.Optional[typing.Sequence[str]] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SubgraphResponse:
        """
        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        depth : typing.Optional[int]

        direction : typing.Optional[str]

        filters : typing.Optional[typing.Dict[str, typing.Any]]

        max_edges : typing.Optional[int]

        max_nodes : typing.Optional[int]

        seed_node_uuids : typing.Optional[typing.Sequence[str]]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubgraphResponse
            OK

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.graph.get_subgraph(
                graph_uuid="graph_uuid",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_subgraph(
            graph_uuid,
            depth=depth,
            direction=direction,
            filters=filters,
            max_edges=max_edges,
            max_nodes=max_nodes,
            seed_node_uuids=seed_node_uuids,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    async def warm(
        self,
        graph_uuid: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncResult:
        """
        Parameters
        ----------
        graph_uuid : str
            Graph UUID

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncResult
            Accepted

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.graph.warm(
                graph_uuid="graph_uuid",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.warm(
            graph_uuid, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    @property
    def document_summary(self):
        if self._document_summary is None:
            from .document_summary.client import AsyncDocumentSummaryClient  # noqa: E402

            self._document_summary = AsyncDocumentSummaryClient(client_wrapper=self._client_wrapper)
        return self._document_summary

    @property
    def episode(self):
        if self._episode is None:
            from .episode.client import AsyncEpisodeClient  # noqa: E402

            self._episode = AsyncEpisodeClient(client_wrapper=self._client_wrapper)
        return self._episode

    @property
    def edge(self):
        if self._edge is None:
            from .edge.client import AsyncEdgeClient  # noqa: E402

            self._edge = AsyncEdgeClient(client_wrapper=self._client_wrapper)
        return self._edge

    @property
    def node(self):
        if self._node is None:
            from .node.client import AsyncNodeClient  # noqa: E402

            self._node = AsyncNodeClient(client_wrapper=self._client_wrapper)
        return self._node

    @property
    def observation(self):
        if self._observation is None:
            from .observation.client import AsyncObservationClient  # noqa: E402

            self._observation = AsyncObservationClient(client_wrapper=self._client_wrapper)
        return self._observation

    @property
    def thread_summary(self):
        if self._thread_summary is None:
            from .thread_summary.client import AsyncThreadSummaryClient  # noqa: E402

            self._thread_summary = AsyncThreadSummaryClient(client_wrapper=self._client_wrapper)
        return self._thread_summary
