shoes = [
    {
        "ranking": "Best Overall",
        "name": "Hoka Mach 5",
        "price": "$140",
        "pros": [
            "New Profly+ midsole is plush and more responsive",
            "Lighter than Mach 4",
        ],
        "cons": ["Little traction in wet and wintry conditions"],
        "key_specs": {
            "Weight": "8.2 oz (M9)",
            "Type": "Neutral Road",
            "Drop": "5 mm",
            "Heel Stack": "29 mm",
            "Forefoot Stack": "24 mm",
        },
        "commentary": "A cushioned road shoe that feels as light and explosive as a race shoe—but still sturdy enough for long training runs. The new Mach 5 uses a tweaked formulation of Profly+ midsole foam for plenty of zoom and bounce.",
    },
    {
        "ranking": "Best for Long Runs",
        "name": "Saucony Triumph 21",
        "price": "$160",
        "pros": [
            "Plush upper with secure midfoot lockdown",
            "Smooth ride and excellent energy return",
            "Good outsole grip and durability",
        ],
        "cons": ["Slightly heavier than Triumph 20", "Toebox feels a bit narrow"],
        "key_specs": {
            "Weight": "9.8 oz (M9)",
            "Type": "Neutral Road",
            "Drop": "10 mm",
            "Heel Stack": "37 mm",
            "Forefoot Stack": "27 mm",
        },
        "commentary": "Triumph 21 received high ratings in every category, offering a cozy fit and interior, with redesigned flat-knit upper and lacing for a more secure fit.",
    },
    {
        "ranking": "Best Update",
        "name": "Asics Gel-Cumulus 25",
        "price": "$140",
        "pros": [
            "Lighter than the Gel-Cumulus 24",
            "Smooth ride with excellent shock absorption",
            "Upper is roomy and soft without feeling sloppy",
        ],
        "cons": ["Runs slightly long", "Upper mesh can trap heat and moisture"],
        "key_specs": {
            "Weight": "9.4 oz (M9)",
            "Type": "Neutral Road",
            "Drop": "8 mm",
            "Heel Stack": "38 mm",
            "Forefoot Stack": "30 mm",
        },
        "commentary": "Gel-Cumulus 25 features Pure Gel for a lighter, softer cushioning, blending in with Flytefoam Blast+ for a smooth landing and shock absorption without extra weight.",
    },
    {
        "ranking": "Best for Road Racing",
        "name": "Nike Vaporfly 3",
        "price": "$260",
        "pros": ["More stable than the Vaporfly 2", "Extremely high energy return"],
        "cons": ["Upper lacks flexibility"],
        "key_specs": {
            "Weight": "7.0 oz (M10)",
            "Type": "Road Racing",
            "Drop": "8 mm",
            "Heel Stack": "40 mm",
            "Forefoot Stack": "32 mm",
        },
        "commentary": "Vaporfly 3 is designed to be light with a carbon-fiber plate and Peba-based foam for top energy return, making every stride efficient and less taxing.",
    },
    {
        "ranking": "Best Budget Shoe",
        "name": "Reebok Floatride Energy 5",
        "price": "$120",
        "pros": [
            "Responsive TPU-based midsole",
            "Midsole plate lends support through toe-off",
            "Good outsole durability",
        ],
        "cons": ["Laces can be difficult to tighten", "Less suited for racing"],
        "key_specs": {
            "Weight": "9.1 oz (M9)",
            "Type": "Neutral Road",
            "Drop": "8 mm",
            "Heel Stack": "27 mm",
            "Forefoot Stack": "19 mm",
        },
        "commentary": "Floatride Energy 5 offers a responsive and versatile performance with a TPU-based midsole and plate for support, praised for its comfort and durability.",
    },
    {
        "ranking": "Best Daily Trainer",
        "name": "New Balance Fresh Foam X 880v13",
        "price": "$111",
        "pros": [
            "Thick, extremely durable outsole rubber",
            "More secure lacing with improved midfoot lockdown",
            "Soft cushioning and smooth ride",
        ],
        "cons": ["Heavier than the 880 v12", "Toebox feels slightly narrower than v12"],
        "key_specs": {
            "Weight": "10.6 oz (M9)",
            "Type": "Neutral Road",
            "Drop": "10 mm",
            "Heel Stack": "32 mm",
            "Forefoot Stack": "22 mm",
        },
        "commentary": "Fresh Foam X 880v13 continues to offer a comfortable ride with dual-density construction for shock absorption and smooth turnover. The update focuses on a snugger fit upper.",
    },
    {
        "ranking": "Best Lightweight Trail Shoe",
        "name": "Hoka Zinal 2",
        "price": "$160",
        "pros": [
            "Lighter than the Zinal v1",
            "Deeper lugs improve grip on muddy trails",
            "Gaiter-style collar keeps out dirt and debris",
        ],
        "cons": ["Some testers wanted more cushioning", "No rock plate"],
        "key_specs": {
            "Weight": "7.4 oz (M9)",
            "Type": "Trail",
            "Drop": "5 mm",
            "Heel Stack": "30 mm",
            "Forefoot Stack": "25 mm",
            "Lug Depth": "5 mm",
        },
        "commentary": "Zinal 2 introduces a new knit ankle collar and Vibram Megagrip Litebase outsole with deeper lugs for improved grip, offering protection and performance on technical terrain.",
    },
    {
        "ranking": "Best for Speedwork",
        "name": "Saucony Kinvara 14",
        "price": "$84",
        "pros": [
            "More breathable upper with locked-in fit",
            "Flexible toe-off and good ground connection",
            "Lighter than the Kinvara 13",
        ],
        "cons": ["Narrow forefoot and toebox", "Less stable than the Kinvara 13"],
        "key_specs": {
            "Weight": "6.8 oz (M9)",
            "Type": "Neutral Road",
            "Drop": "4 mm",
            "Heel Stack": "31 mm",
            "Forefoot Stack": "27 mm",
        },
        "commentary": "Kinvara 14 is designed as a do-it-all shoe, adding cushioning for comfort while maintaining a light weight for speed, making it versatile for both daily training and racing.",
    },
    {
        "ranking": "Best Cushioned Trail Shoe",
        "name": "Salomon Thundercross",
        "price": "$140",
        "pros": [
            "Quick-lacing allows for fast adjustments",
            "New lug pattern provides excellent grip on muddy terrain",
            "Durable, hydrophobic upper material",
            "New midsole foam feels softer",
        ],
        "cons": ["On the heavier side", "Upper is less breathable"],
        "key_specs": {
            "Weight": "10.0 oz (M9)",
            "Type": "Trail",
            "Drop": "4 mm",
            "Heel Stack": "31 mm",
            "Forefoot Stack": "27 mm",
            "Lug Depth": "5 mm",
        },
        "commentary": "Thundercross is designed for protection and grip in all conditions, combining the comfort of Salomon's Sense Ride with the technical terrain capabilities of the Speedcross.",
    },
    {
        "ranking": "Best Stability Shoe",
        "name": "Brooks Adrenaline GTS 23",
        "price": "$140",
        "pros": ["Good arch support", "Lighter than the Adrenaline GTS 22"],
        "cons": ["Less suited for speed workouts"],
        "key_specs": {
            "Weight": "10.1 oz (M9)",
            "Type": "Stability Road",
            "Drop": "12 mm",
            "Heel Stack": "36 mm",
            "Forefoot Stack": "24 mm",
        },
        "commentary": "Adrenaline GTS 23 continues to offer stability with a less obtrusive GuideRails system, now featuring new DNA Loft v2 foam for a softer, smoother ride.",
    },
    {
        "ranking": "Best Road-to-Trail Hybrid",
        "name": "Nike Pegasus Trail 4 GTX",
        "price": "$160",
        "pros": [
            "Bouncy React midsole provides high energy return",
            "Partial gaiter collar keeps out trail debris",
            "Transitions smoothly from trail to road",
        ],
        "cons": [
            "3.5mm lugs are less suited for deep mud",
            "Some testers wanted more rock protection",
        ],
        "specifications": {
            "Weight": "9.8 oz (M), 7.9 oz (W)",
            "Drop": "9.5 mm (M), 8.5 mm (W)",
            "Type": "Road and Trail",
        },
    },
    {
        "ranking": "Best for Long Runs",
        "name": "Topo Athletic Ultraventure 3",
        "price": "$150",
        "pros": [
            "Good road-to-trail versatility",
            "Gaiter compatible",
            "Lighter and more responsive than v2",
        ],
        "cons": ["Tongue is slightly short", "$15 price bump from v2"],
        "specifications": {
            "Weight": "10.1 oz (M), 8.2 oz (W)",
            "Drop": "5 mm",
            "Type": "Trail",
        },
    },
    {
        "ranking": "Best for Steep Climbs",
        "name": "Hoka Mafate Speed 4",
        "price": "$185",
        "pros": [
            "Soft midsole for long run comfort",
            "5mm Vibram lugs stick to rocks and dirt",
            "Roomy fit",
        ],
        "cons": [
            "$5 price bump from Mafate Speed 3",
            "Upper design isn’t for everybody",
        ],
        "specifications": {
            "Weight": "10.4 oz (M), 8.4 oz (W)",
            "Drop": "4 mm",
            "Type": "Trail",
        },
    },
    {
        "ranking": "Firm and Fast",
        "name": "Brooks Catamount 2",
        "price": "$110",
        "pros": [
            "4mm lugs are grippier, wider than v1",
            "Hydrophobic mesh upper repels water",
        ],
        "cons": ["Longer, narrower fit than most Brooks shoes"],
        "specifications": {
            "Weight": "9.4 oz (M), 7.7 oz (W)",
            "Drop": "6 mm",
            "Type": "Trail",
        },
    },
    {
        "ranking": "Best for Wide Feet",
        "name": "Altra Lone Peak 7",
        "price": "$85",
        "pros": [
            "Wide, comfortable toebox",
            "Forefoot rock plate",
            "Longer lugs than Lone Peak 6 (now 5mm)",
        ],
        "cons": [
            "Slightly heavier than Lone Peak 6",
            "Transition gradually to zero-drop platform",
        ],
        "specifications": {
            "Weight": "10.5 oz (M), 8.3 oz (W)",
            "Drop": "0 mm",
            "Type": "Trail",
        },
    },
    {
        "ranking": "Best Plated Trail Shoe",
        "name": "Salomon Pulsar Trail",
        "price": "$105",
        "pros": [
            "Excellent traction on both wet and dry trails",
            "Midsole plate feels stable and responsive",
        ],
        "cons": ["3.5mm lugs are less suited for deep mud"],
        "specifications": {
            "Weight": "9.8 oz (M), 8.5 oz (W)",
            "Drop": "6 mm",
            "Type": "Trail",
        },
    },
    {
        "ranking": "Best All-Arounder",
        "name": "Saucony Peregrine 13",
        "price": "$69",
        "pros": [
            "5mm lugs shed mud easily",
            "Available in multiple versions (GTX, Soft Terrain, ICE+) and widths",
            "Responsive, nimble ride with excellent grip",
            "Slightly softer midsole cushioning than v12",
        ],
        "cons": ["Collar can rub around the heel", "$10 price increase from v12"],
        "specifications": {
            "Weight": "9.2 oz (M), 7.9 oz (W)",
            "Drop": "4 mm",
            "Type": "Trail",
        },
    },
    {
        "ranking": "Springy with Ground Feel",
        "name": "Inov-8 Trailfly G 270 v2",
        "price": "$150",
        "pros": [
            "Widened toebox and stretchy mesh upper feel comfortable for longer runs",
            "Extremely durable Graphene outsole",
            "4mm lugs are versatile for hard ground",
        ],
        "cons": ["Transition gradually to zero-drop platform", "No rock plate"],
        "specifications": {
            "Weight": "9.1 oz (M), 7.3 oz (W)",
            "Drop": "0 mm",
            "Type": "Trail",
        },
    },
    {
        "ranking": "Best for Uneven Terrain",
        "name": "La Sportiva Bushido II",
        "price": "$100",
        "pros": [
            "Rubber toe cap and forefoot rockplate for protection",
            "Firm and stable ride",
            "Also available in GTX version",
        ],
        "cons": ["Upper is not especially breathable", "Modest lug length at 3.5mm"],
        "specifications": {
            "Weight": "10.5 oz (M), 8.8 oz (W)",
            "Drop": "6 mm",
            "Type": "Trail",
        },
    },
    {
        "ranking": "Best Deal",
        "name": "Merrell Moab Flight",
        "price": "$122",
        "pros": [
            "Grippy Vibram rubber outsole",
            "3mm lugs are modest, but capable on wet terrain",
            "Good upper durability",
        ],
        "cons": ["Less suited for racing and faster efforts", "Upper traps some heat"],
        "specifications": {
            "Weight": "9.9 oz (M), 8.1 oz (W)",
            "Drop": "10 mm",
            "Type": "Trail",
        },
    },
    {
        "ranking": "Best Traction Overall",
        "name": "VJ Ultra 2",
        "price": "$170",
        "pros": [
            "Excellent traction on both wet and dry trails",
            "Unlike the first version, now has a rockplate",
            "Good upper durability and secure fit",
        ],
        "cons": ["Less energy return", "Cheap-feeling laces for a $170 shoe"],
        "specifications": {
            "Weight": "9.6 oz (M), 7.9 oz (W)",
            "Drop": "6 mm",
            "Type": "Trail",
        },
    },
]
