# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pagination import AsyncPager, SyncPager
from ..core.request_options import RequestOptions
from ..types.batch import Batch
from ..types.batch_items_response import BatchItemsResponse
from ..types.batch_page import BatchPage
from ..types.json_object import JsonObject
from ..types.json_object_page import JsonObjectPage
from ..types.process_batch_result import ProcessBatchResult
from .raw_client import AsyncRawBatchClient, RawBatchClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class BatchClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawBatchClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawBatchClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawBatchClient
        """
        return self._raw_client

    def list(
        self,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        status: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[Batch, BatchPage]:
        """
        Parameters
        ----------
        limit : typing.Optional[int]
            Page size

        cursor : typing.Optional[str]
            Opaque page cursor

        status : typing.Optional[str]
            Batch status filter

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[Batch, BatchPage]
            OK

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        response = client.batch.list(
            limit=1,
            cursor="cursor",
            status="status",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list(limit=limit, cursor=cursor, status=status, request_options=request_options)

    def create(
        self,
        *,
        ignore_roles: typing.Optional[typing.Sequence[str]] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        strict_ontology: typing.Optional[bool] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Batch:
        """
        Parameters
        ----------
        ignore_roles : typing.Optional[typing.Sequence[str]]

        metadata : typing.Optional[typing.Dict[str, typing.Any]]

        strict_ontology : typing.Optional[bool]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Batch
            Created

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        client.batch.create()
        """
        _response = self._raw_client.create(
            ignore_roles=ignore_roles,
            metadata=metadata,
            strict_ontology=strict_ontology,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    def get(self, batch_uuid: str, *, request_options: typing.Optional[RequestOptions] = None) -> Batch:
        """
        Parameters
        ----------
        batch_uuid : str
            Batch UUID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Batch
            OK

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        client.batch.get(
            batch_uuid="batch_uuid",
        )
        """
        _response = self._raw_client.get(batch_uuid, request_options=request_options)
        return _response.data

    def delete(
        self,
        batch_uuid: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Parameters
        ----------
        batch_uuid : str
            Batch UUID

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        client.batch.delete(
            batch_uuid="batch_uuid",
        )
        """
        _response = self._raw_client.delete(
            batch_uuid, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    def list_items(
        self,
        batch_uuid: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[JsonObject, JsonObjectPage]:
        """
        Parameters
        ----------
        batch_uuid : str
            Batch UUID

        limit : typing.Optional[int]
            Page size

        cursor : typing.Optional[str]
            Opaque page cursor

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[JsonObject, JsonObjectPage]
            OK

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        response = client.batch.list_items(
            batch_uuid="batch_uuid",
            limit=1,
            cursor="cursor",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list_items(batch_uuid, limit=limit, cursor=cursor, request_options=request_options)

    def add_items(
        self,
        batch_uuid: str,
        *,
        items: typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BatchItemsResponse:
        """
        Parameters
        ----------
        batch_uuid : str
            Batch UUID

        items : typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BatchItemsResponse
            OK

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        client.batch.add_items(
            batch_uuid="batch_uuid",
        )
        """
        _response = self._raw_client.add_items(
            batch_uuid, items=items, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    def process(
        self,
        batch_uuid: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ProcessBatchResult:
        """
        Parameters
        ----------
        batch_uuid : str
            Batch UUID

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProcessBatchResult
            Accepted

        Examples
        --------
        from zep_cloud import Zep

        client = Zep(
            api_key="YOUR_API_KEY",
        )
        client.batch.process(
            batch_uuid="batch_uuid",
        )
        """
        _response = self._raw_client.process(
            batch_uuid, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data


class AsyncBatchClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawBatchClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawBatchClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawBatchClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        status: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[Batch, BatchPage]:
        """
        Parameters
        ----------
        limit : typing.Optional[int]
            Page size

        cursor : typing.Optional[str]
            Opaque page cursor

        status : typing.Optional[str]
            Batch status filter

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[Batch, BatchPage]
            OK

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.batch.list(
                limit=1,
                cursor="cursor",
                status="status",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list(limit=limit, cursor=cursor, status=status, request_options=request_options)

    async def create(
        self,
        *,
        ignore_roles: typing.Optional[typing.Sequence[str]] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        strict_ontology: typing.Optional[bool] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Batch:
        """
        Parameters
        ----------
        ignore_roles : typing.Optional[typing.Sequence[str]]

        metadata : typing.Optional[typing.Dict[str, typing.Any]]

        strict_ontology : typing.Optional[bool]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Batch
            Created

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.batch.create()


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            ignore_roles=ignore_roles,
            metadata=metadata,
            strict_ontology=strict_ontology,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    async def get(self, batch_uuid: str, *, request_options: typing.Optional[RequestOptions] = None) -> Batch:
        """
        Parameters
        ----------
        batch_uuid : str
            Batch UUID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Batch
            OK

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.batch.get(
                batch_uuid="batch_uuid",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(batch_uuid, request_options=request_options)
        return _response.data

    async def delete(
        self,
        batch_uuid: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Parameters
        ----------
        batch_uuid : str
            Batch UUID

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.batch.delete(
                batch_uuid="batch_uuid",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(
            batch_uuid, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    async def list_items(
        self,
        batch_uuid: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[JsonObject, JsonObjectPage]:
        """
        Parameters
        ----------
        batch_uuid : str
            Batch UUID

        limit : typing.Optional[int]
            Page size

        cursor : typing.Optional[str]
            Opaque page cursor

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[JsonObject, JsonObjectPage]
            OK

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.batch.list_items(
                batch_uuid="batch_uuid",
                limit=1,
                cursor="cursor",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list_items(
            batch_uuid, limit=limit, cursor=cursor, request_options=request_options
        )

    async def add_items(
        self,
        batch_uuid: str,
        *,
        items: typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BatchItemsResponse:
        """
        Parameters
        ----------
        batch_uuid : str
            Batch UUID

        items : typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BatchItemsResponse
            OK

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.batch.add_items(
                batch_uuid="batch_uuid",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.add_items(
            batch_uuid, items=items, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    async def process(
        self,
        batch_uuid: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ProcessBatchResult:
        """
        Parameters
        ----------
        batch_uuid : str
            Batch UUID

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProcessBatchResult
            Accepted

        Examples
        --------
        import asyncio

        from zep_cloud import AsyncZep

        client = AsyncZep(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.batch.process(
                batch_uuid="batch_uuid",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.process(
            batch_uuid, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data
