# This file was auto-generated by Fern from our API Definition.

from ..core.api_error import ApiError
from ..types.apihandlers_api_error import ApihandlersApiError


class UnauthorizedError(ApiError):
    def __init__(self, body: ApihandlersApiError):
        super().__init__(status_code=401, body=body)
